version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=auth-db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=auth_db
    depends_on:
      - auth-db

  auth-db:
    image: postgres:13
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - auth-db

volumes:
  auth-db-data:
